name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Whether to deploy up or down"
        required: true
        default: "up"
        type: choice
        options:
          - up
          - down
      stack:
        description: "The stack to deploy up or down. (Leave blank for default)"
        default: ""

jobs:
  defang:
    name: Defang ${{ github.event.inputs.action || 'up' }} ${{
      github.event.inputs.stack || 'default stack' }}
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    concurrency:
      cancel-in-progress: false
      group: deploy-${{ github.event.inputs.stack || 'default' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download defang binary
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          gh auth login
          gh release download testoidcnocgo --repo edwardrf/testactions --pattern defang
          chmod +x defang
          ls -lah
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Defang login
        run: |
          ls -la defang
          ./defang login
          ./defang whoami
          ./defang cd ls --stack=production

#      - name: Defang ${{ github.event.inputs.action || 'up' }} ${{
#          github.event.inputs.stack || 'default stack' }}
#        uses: DefangLabs/defang-github-action@v1.4.0
#        with:
#          cli-version: v3.3.0
#          command: ${{ github.event.inputs.action || 'up' }}
#          stack: ${{ github.event.inputs.stack || '' }}

#      - name: Deployment Summary
#        uses: DefangLabs/defang-github-action@v1.4.0
#        with:
#          command: services
#          stack: ${{ github.event.inputs.stack || '' }}
